#!/bin/sh
#
# DESCRIPTION
#
# Startup init script for BackupPC on suse linux.
#
# Distributed with BackupPC version 4.0.0alpha3, released 1 Dec 2013.
#

set -e

#
BINDIR=/usr/share/backuppc/bin
DATADIR=/var/lib/backuppc
LOGDIR=/var/lib/backuppc/log
USER=backuppc
#
NAME=backuppc
DAEMON=BackupPC

test -x $BINDIR/$DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $NAME: "
    startproc -f  -p $LOGDIR/BackupPC.pid -u $USER $BINDIR/$DAEMON -d 
    echo "ok."
    ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $LOGDIR/BackupPC.pid -u $USER \
			    --oknodo 
    echo "ok."
      ;;
  restart)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $LOGDIR/BackupPC.pid -u $USER \
			    --oknodo 
    echo "ok."
    echo -n "Starting $NAME: "
    startproc -f  -p $LOGDIR/BackupPC.pid -u $USER $BINDIR/$DAEMON -d 
    echo "ok."
    ;;
  reload|force-reload)
    echo "Reloading $NAME configuration files"
    start-stop-daemon --stop --pidfile $LOGDIR/BackupPC.pid \
			    --signal 1 -x /usr/bin/perl
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0
